//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal partial class CourseDescription
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
        public CourseDescription()
        {
            this.CourseInstances = new HashSet<CourseInstance>();
        }
    
    	private System.Guid _id;
        public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}
    	private string _coursename;
        public  string CourseName 
		{ 
			get
			{ 
				return _coursename; 
			} 
			set
			{
				_coursename = value;
				ObjectPropertyChanged("CourseName");
			}
		}
    	private string _description;
        public  string Description 
		{ 
			get
			{ 
				return _description; 
			} 
			set
			{
				_description = value;
				ObjectPropertyChanged("Description");
			}
		}
    	private System.Guid _organizationid;
        public  System.Guid OrganizationId 
		{ 
			get
			{ 
				return _organizationid; 
			} 
			set
			{
				_organizationid = value;
				ObjectPropertyChanged("OrganizationId");
			}
		}
    	private string _coursenumber;
        public  string CourseNumber 
		{ 
			get
			{ 
				return _coursenumber; 
			} 
			set
			{
				_coursenumber = value;
				ObjectPropertyChanged("CourseNumber");
			}
		}
    	private bool _active;
        public  bool Active 
		{ 
			get
			{ 
				return _active; 
			} 
			set
			{
				_active = value;
				ObjectPropertyChanged("Active");
			}
		}
    
        public virtual Organization Organization { get; set; }
        public virtual ICollection<CourseInstance> CourseInstances { get; set; }
    }
}
