//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal partial class CourseInstance
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
        public CourseInstance()
        {
            this.ClassGroups = new HashSet<ClassGroup>();
        }
    
    	private System.Guid _id;
        public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}
    	private System.Guid _courseid;
        public  System.Guid CourseId 
		{ 
			get
			{ 
				return _courseid; 
			} 
			set
			{
				_courseid = value;
				ObjectPropertyChanged("CourseId");
			}
		}
    	private System.Guid _regionid;
        public  System.Guid RegionId 
		{ 
			get
			{ 
				return _regionid; 
			} 
			set
			{
				_regionid = value;
				ObjectPropertyChanged("RegionId");
			}
		}
    	private string _coursecode;
        public  string CourseCode 
		{ 
			get
			{ 
				return _coursecode; 
			} 
			set
			{
				_coursecode = value;
				ObjectPropertyChanged("CourseCode");
			}
		}
    	private string _courseleader;
        public  string CourseLeader 
		{ 
			get
			{ 
				return _courseleader; 
			} 
			set
			{
				_courseleader = value;
				ObjectPropertyChanged("CourseLeader");
			}
		}
    	private bool _active;
        public  bool Active 
		{ 
			get
			{ 
				return _active; 
			} 
			set
			{
				_active = value;
				ObjectPropertyChanged("Active");
			}
		}
    
        public virtual ICollection<ClassGroup> ClassGroups { get; set; }
        public virtual CourseDescription CourseDescription { get; set; }
        public virtual Region Region { get; set; }
    }
}
