//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal partial class Member
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
        public Member()
        {
            this.Attendances = new HashSet<Attendance>();
        }
    
    	private int _id;
        public  int Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}
    	private System.Guid _organizationid;
        public  System.Guid OrganizationId 
		{ 
			get
			{ 
				return _organizationid; 
			} 
			set
			{
				_organizationid = value;
				ObjectPropertyChanged("OrganizationId");
			}
		}
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
