//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal partial class Region
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
        public Region()
        {
            this.CourseInstances = new HashSet<CourseInstance>();
            this.Suburbs = new HashSet<Suburb>();
        }
    
    	private System.Guid _id;
        public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}
    	private System.Guid _organizationid;
        public  System.Guid OrganizationId 
		{ 
			get
			{ 
				return _organizationid; 
			} 
			set
			{
				_organizationid = value;
				ObjectPropertyChanged("OrganizationId");
			}
		}
    	private string _regionname;
        public  string RegionName 
		{ 
			get
			{ 
				return _regionname; 
			} 
			set
			{
				_regionname = value;
				ObjectPropertyChanged("RegionName");
			}
		}
    	private bool _active;
        public  bool Active 
		{ 
			get
			{ 
				return _active; 
			} 
			set
			{
				_active = value;
				ObjectPropertyChanged("Active");
			}
		}
    
        public virtual ICollection<CourseInstance> CourseInstances { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<Suburb> Suburbs { get; set; }
    }
}
