//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal partial class Session
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
        public Session()
        {
            this.Attendances = new HashSet<Attendance>();
        }
    
    	private System.Guid _id;
        public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}
    	private System.Guid _classgroupid;
        public  System.Guid ClassGroupId 
		{ 
			get
			{ 
				return _classgroupid; 
			} 
			set
			{
				_classgroupid = value;
				ObjectPropertyChanged("ClassGroupId");
			}
		}
    	private System.Guid _areaid;
        public  System.Guid AreaId 
		{ 
			get
			{ 
				return _areaid; 
			} 
			set
			{
				_areaid = value;
				ObjectPropertyChanged("AreaId");
			}
		}
    	private System.DateTime _date;
        public  System.DateTime Date 
		{ 
			get
			{ 
				return _date; 
			} 
			set
			{
				_date = value;
				ObjectPropertyChanged("Date");
			}
		}
    	private bool _active;
        public  bool Active 
		{ 
			get
			{ 
				return _active; 
			} 
			set
			{
				_active = value;
				ObjectPropertyChanged("Active");
			}
		}
    
        public virtual Area Area { get; set; }
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ClassGroup ClassGroup { get; set; }
    }
}
