//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal partial class Suburb
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
        public Suburb()
        {
            this.Active = true;
            this.Venues = new HashSet<Venue>();
        }
    
    	private System.Guid _id;
        public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}
    	private string _suburbname;
        public  string SuburbName 
		{ 
			get
			{ 
				return _suburbname; 
			} 
			set
			{
				_suburbname = value;
				ObjectPropertyChanged("SuburbName");
			}
		}
    	private string _postcode;
        public  string Postcode 
		{ 
			get
			{ 
				return _postcode; 
			} 
			set
			{
				_postcode = value;
				ObjectPropertyChanged("Postcode");
			}
		}
    	private System.Guid _regionid;
        public  System.Guid RegionId 
		{ 
			get
			{ 
				return _regionid; 
			} 
			set
			{
				_regionid = value;
				ObjectPropertyChanged("RegionId");
			}
		}
    	private bool _active;
        public  bool Active 
		{ 
			get
			{ 
				return _active; 
			} 
			set
			{
				_active = value;
				ObjectPropertyChanged("Active");
			}
		}
    
        public virtual Region Region { get; set; }
        public virtual ICollection<Venue> Venues { get; set; }
    }
}
