//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal partial class Venue
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
        public Venue()
        {
            this.Areas = new HashSet<Area>();
        }
    
    	private System.Guid _id;
        public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}
    	private string _venuename;
        public  string VenueName 
		{ 
			get
			{ 
				return _venuename; 
			} 
			set
			{
				_venuename = value;
				ObjectPropertyChanged("VenueName");
			}
		}
    	private string _venueaddress;
        public  string VenueAddress 
		{ 
			get
			{ 
				return _venueaddress; 
			} 
			set
			{
				_venueaddress = value;
				ObjectPropertyChanged("VenueAddress");
			}
		}
    	private System.Guid _suburbid;
        public  System.Guid SuburbId 
		{ 
			get
			{ 
				return _suburbid; 
			} 
			set
			{
				_suburbid = value;
				ObjectPropertyChanged("SuburbId");
			}
		}
    	private bool _active;
        public  bool Active 
		{ 
			get
			{ 
				return _active; 
			} 
			set
			{
				_active = value;
				ObjectPropertyChanged("Active");
			}
		}
    
        public virtual ICollection<Area> Areas { get; set; }
        public virtual Suburb Suburb { get; set; }
    }
}
